spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mjk
    username: mjk
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379

  security:
    login-url: /login
    redirect-url: ${REDIRECT_URL:/}
    cookie:
      domain: ${COOKIE_DOMAIN:localhost}
      secure: ${COOKIE_SECURE:false}
      http-only: ${COOKIE_HTTP_ONLY:true}

    oauth2:
      client:
        registration:
          google:
            client-id: 859762639227-eati0e1s319f02p8u8torvqf8m74v71v.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
            authorization-grant-type: authorization_code

# === S3 설정 추가 ===
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET:your-bucket-name}
    credentials:
      access-key: ${AWS_ACCESS_KEY:your-access-key}
      secret-key: ${AWS_SECRET_KEY:your-secret-key}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

jwt:
  secret-key: ${JWT_SECRET_KEY:apsxhtmvmfhwprxmghkdlxldrnfmagozjxhsghkdlxld12345}
  expiration-time:
    access-token: ${JWT_EXPIRATION_TIME_ACCESS_TOKEN:3600}
    refresh-token: ${JWT_EXPIRATION_TIME_REFRESH_TOKEN:7776000}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
