name: Java CI with Gradle

# 동작 조건 설정 : main 브랜치에 push 혹은 pull request가 발생할 경우 동작한다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 1. Java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application-local.yml
      run: |
        cd ./src/main/resources
        touch application-local.yml
        echo "$YML_LOCAL" > application-local.yml
      shell: bash
      env:
        YML_LOCAL: ${{ secrets.YML_LOCAL }}

    # 2. Spring Boot 애플리케이션 빌드
    - name: Build with Gradle (without test)
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build -x test


    # 3. Docker 이미지 빌드
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent .

    # 4. DockerHub 로그인
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 5. Docker Hub 이미지 푸시
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent
      
  run-docker-image-on-ec2:
      # build-docker-image (위)과정이 완료되어야 실행됩니다.
      needs: build-docker-image
      runs-on: self-hosted
  
      steps:      
        # 1. 최신 이미지를 pull
        - name: docker pull
          run: sudo docker pull y2jun/mjk_agent

        # 2. 기존 Spring Boot 컨테이너 중지 및 삭제
        - name: docker stop & remove old container
          run: |
            sudo docker ps -a --filter "ancestor=y2jun/mjk_agent" --format "{{.ID}}" | \
            xargs -r -I {} sudo sh -c 'docker stop {} && docker rm {}'

        # 3. Redis 컨테이너 확인 및 실행
        - name: ensure redis container exists
          run: |
            sudo docker ps -a --format '{{.Names}}' | grep -q '^redis$' || \
              sudo docker run -d --name redis --network my-network -p 6379:6379 -v redis-data:/data redis:latest

        # 4. Spring Boot 컨테이너 실행
        - name: docker run new container
          run: |
            sudo docker run -d \
              -p 8080:8080 \
              --network my-network \
              -e REDIS_HOST=redis \
              y2jun/mjk_agent:latest

        # 5. 미사용 이미지 정리
        - name: delete old docker image
          run: sudo docker system prune -f
