name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application-local.yml
      run: |
        cd ./src/main/resources
        touch application-local.yml
        echo "$YML_LOCAL" > application-local.yml
      shell: bash
      env:
        YML_LOCAL: ${{ secrets.YML_LOCAL }}

    - name: Build with Gradle (without test)
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build -x test

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest
      
  run-docker-image-on-ec2:
      needs: build-docker-image
      runs-on: self-hosted
  
      steps:
        - name: docker pull latest image
          run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest
            sudo docker ps -a --format "{{.ID}} {{.Ports}}" | grep '0.0.0.0:8080' | awk '{print $1}' | \
            xargs -r -I {} sudo sh -c 'docker stop {} && docker rm {}'


        - name: ensure redis container exists
          run: |
            sudo docker ps -a --format '{{.Names}}' | grep -q '^redis$' || \
              sudo docker run -d --name redis --network my-network -p 6379:6379 -v redis-data:/data redis:latest

        - name: run new container
          run: |
            sudo docker run -d \
              -p 8080:8080 \
              --network my-network \
              -e REDIS_HOST=redis \
              ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest

        - name: delete old docker image
          run: sudo docker system prune -f
