name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/settings.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make application-local.yml
        run: |
          cd ./src/main/resources
          touch application-local.yml
          echo "$YML_LOCAL" > application-local.yml
        shell: bash
        env:
          YML_LOCAL: ${{ secrets.YML_LOCAL }}

      - name: Build with Gradle (without test)
        uses: gradle/gradle-build-action@v1
        with:
          arguments: clean build -x test

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Docker pull latest image
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest

      - name: Stop & remove all containers
        run: |
          sudo docker ps -aq | xargs -r sudo docker stop
          sudo docker ps -aq | xargs -r sudo docker rm

      - name: Remove redis volume (optional)
        run: sudo docker volume rm redis-data || true

      - name: Create Docker network if not exists
        run: sudo docker network create my-network || true

      - name: Run Redis container
        run: |
          sudo docker run -d \
            --name redis \
            --network my-network \
            -p 6379:6379 \
            -v redis-data:/data \
            redis:latest

      - name: Run Spring Boot container
        run: |
          sudo docker run -d \
            --name mjk_agent \
            --network my-network \
            -p 8080:8080 \
            -e REDIS_HOST=redis \
            ${{ secrets.DOCKERHUB_USERNAME }}/mjk_agent:latest

      - name: Prune unused docker data
        run: sudo docker system prune -f
